modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/jezielcamara/cobble-spawn-control/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/jezielcamara/cobble-spawn-control"
authors="CobbleWorld"
description='''
World-scale wild Pokemon population, ecology, rarity, density, and level control for Cobblemon.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemon"
type="required"
versionRange="[1.8.1,1.9)"
ordering="AFTER"
side="BOTH"

[features.${mod_id}]
javaVersion="[21,22)"
